### ISSUE TITLE
Support for installing/upgrading IFAX firmware would be nice addition

### ISSUE THREAD

**Issue by phdonnelly** [CauldronDevelopmentLLC/oh-brother#10]
If you're not aware, brother offers an optional sub-firmware on some of its models to allow scan to email via SMTP instead of via mail client, they refer to the firmware as IFAX in their tools and whatnot.

Searching for the correct firmware file and uploading to the printer is performed exactly as the other firmwares BUT this current IFAX firmware version is not exposed via SNMP as far as I can see. Looking at packet captures from the brother tool, they send a command via IPP which then lists the IFAX firmware version number, if present.

Currently I use a hacked-up version of this script which always updates the IFAX firmware if the MAIN firmware is out of date, which is suboptimal, but I could post if needed.

Here is an example XML query which provides a IFAX firmware location for a L2740DW, basically you set category to IFAX, leave FIRMINFO ID set to main, and drop in the current IFAX version.

```
<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>IFAX</FIRMCATEGORY>
        <OS>LINUX</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>
    <FIRMUPDATEINFO>
        <MODELINFO>
            <SELIALNO>ABC123</SELIALNO>
            <NAME>MFC-L2740DW series</NAME>
            <SPEC>0001</SPEC>
            <DRIVER />
            <FIRMINFO>
              <FIRM><ID>MAIN</ID><VERSION>i0801170900</VERSION></FIRM>
            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT />
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>
```

**Comment by Wikinaut** [comment]
@phdonnelly perhaps you can help me with my ADS-2600We scanner, where the SUB2 update appears to have a problem finding the firmware, see #11

**Comment by jcoffland** [comment]
I would accept a PR which allowed you to specify a hard coded firmware type and category.

**Comment by jcoffland** [comment]
Try this:

    ./oh-brother.py --category IFAX <printer IP>

**Comment by phdonnelly** [comment]
Hi,

Sorry for the huge delay getting back to this; the new category command works great except for one small tweak; for the IFAX firmware XML, the firmware ID has to be set to "MAIN" EVEN though we're not requesting the main firmware, so we have to special case this and force the ID to "MAIN" for this call to return correct data.

replacing this line:

  ET.SubElement(firm, 'ID').text = cat

with this:

  if(cat == "IFAX"):
    ET.SubElement(firm, 'ID').text = "MAIN"
  else:
    ET.SubElement(firm, 'ID').text = cat

allows this to work.

**Comment by jcoffland** [comment]
Could you submit a PR for this?
