### ISSUE TITLE
Brother Scanner ADS-2600We SUB Version issue (SUB version was -perhaps- not upgraded from C to D)

### ISSUE THREAD

**Issue by Wikinaut** [CauldronDevelopmentLLC/oh-brother#11]
With your appreciated tool I successfully upgraded the main firmware of my ADS-2600We scanner from version G/C to H/C, but the BROTHER download webpage says, that the current version is "H/**D**", see firmware information links
* http://support.brother.com/g/b/downloadlist.aspx?c=eu_ot&lang=en&prod=ads2600we_eu_as_cn&os=7
* http://support.brother.com/g/b/downloadlist.aspx?c=eu_ot&lang=en&prod=ads2600we_eu_as_cn&os=7#SelectLanguageType-375_0_1

Please can you help, is it a problem of their website info, or perhaps a problem in your code ?

Here is the output of my update run:

```
$ ./oh-brother.py xxx.xxx.xxx.xxx
Getting SNMP data from printer at xxx.xxx.xxx.xxx ...
done

      serial = zzzzzzzzzzzzzzzzzzzz
       model = ADS-2600We
        spec = 0103
   firmwares
            category = MAIN, version = G1601190055:7877
            category = SUB2, version = C14112610


Updating MAIN version G1601190055:7877
Looking up printer firmware info at vendor server...
done
Downloading firmware file LZ5400_H.djf from vendor server...
......................................................................done
About to upload the firmware to printer.
This is a dangerous action since it is potentially destructive.
Thus please double-check / review to ensure that:
- firmware file version is compatible with your hardware
- network connection is maximally reliable (strongly prefer wired connection to WLAN)
- power supply is maximally reliable (may be achieved by using a UPS)
Press Ctrl-C to prevent firmware upgrade, or possibly Enter to continue...

Enter printer admin password: 
Now uploading firmware to printer (DO NOT REMOVE POWER!)...
done

Wait for printer to finish updating and reboot before continuing.
Press Enter to continue...

Updating SUB2 version C14112610
Looking up printer firmware info at vendor server...
done
No firmware update info path found
```

Here is the relevant debug output:
```
Updating SUB2 version C14112610
request: <?xml version='1.0' encoding='utf8'?>
<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>MAIN</FIRMCATEGORY>
        <OS>LINUX</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>
    <FIRMUPDATEINFO>
        <MODELINFO>
            <SELIALNO>zzzzzzzzzzzzz</SELIALNO>
            <NAME>ADS-2600We</NAME>
            <SPEC>0103</SPEC>
            <DRIVER />
            <FIRMINFO>
              <FIRM><ID>SUB2</ID><VERSION>C14112610</VERSION></FIRM>
            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT />
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>
Looking up printer firmware info at vendor server...
done
response: <?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO><FIRMUPDATEINFO><VERSIONCHECK>2</VERSIONCHECK></FIRMUPDATEINFO></RESPONSEINFO>
<?xml version="1.0" ?>
<RESPONSEINFO>
 <FIRMUPDATEINFO>
  <VERSIONCHECK>2</VERSIONCHECK>
 </FIRMUPDATEINFO>
</RESPONSEINFO>

No firmware update info path found
```

**Comment by Wikinaut** [comment]
@jcoffland Question

In the REQUESTINFO block, is `<FIRMCATEGORY>MAIN</FIRMCATEGORY>` correct ?

Or has it to be changed to `<FIRMCATEGORY>SUB</FIRMCATEGORY>` ??

**Comment by jcoffland** [comment]
You are right the ``FIRMCATEGORY`` should be ``SUB2``.  I previously accepted a PR which changed some related code.  I've rolled back that change.  Please try the updated code.

**Comment by Wikinaut** [comment]
I am just trying, but response is always "2" (not found)

**Comment by Wikinaut** [comment]
...one moment. Will use updated code.

**Comment by Wikinaut** [comment]
Negative. I think, soemthing is wrong with this special SUB2 request.

Using 4a879d2afd3364112285876bb95d279b2fea56fc I also got

```
Updating SUB2 version C14112610
request: <?xml version='1.0' encoding='utf8'?>
<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>SUB2</FIRMCATEGORY>
        <OS>LINUX</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>
    <FIRMUPDATEINFO>
        <MODELINFO>
            <SELIALNO>zzzzzzz</SELIALNO>
            <NAME>ADS-2600We</NAME>
            <SPEC>0103</SPEC>
            <DRIVER />
            <FIRMINFO>
              <FIRM><ID>SUB2</ID><VERSION>C14112610</VERSION></FIRM>
            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT />
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>
Looking up printer firmware info at vendor server...
done
<?xml version="1.0" ?>
<RESPONSEINFO>
 <FIRMUPDATEINFO>
  <VERSIONCHECK>2</VERSIONCHECK>
  <FIRMID>SUB2</FIRMID>
 </FIRMUPDATEINFO>
</RESPONSEINFO>

No firmware update info path found

```

**Comment by Wikinaut** [comment]
This is, what I also got by manually crafting this request.

**Comment by Wikinaut** [comment]
I already tried some other things, but is there a way to get a "catalogue" or "list" of available resources ?

**Comment by jcoffland** [comment]
Your guess is as good as mine.  If Brother wont return the path to the firmware then the tool wont work.

**Comment by jcoffland** [comment]
Let me know if you can figure out how to get the firmware server to return the firmware path.

**Comment by Wikinaut** [comment]
Here (source: https://cbompart.wordpress.com/2014/05/26/brother-printer-firmware-part-2/ when trying for `$ ./fetch.sh -n "MFC-9340CDW" -s 0502 -f MAIN,SUB1,SUB2,IFAX `I found that 
`<VERSION>B0000000000</VERSION>`apparently forces a list:

```
<?xml version='1.0' encoding='utf8'?>
<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>SUB2</FIRMCATEGORY>
        <OS>LINUX</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>
    <FIRMUPDATEINFO>
        <MODELINFO>
            <SELIALNO>zzzzzzz</SELIALNO>
            <NAME>ADS-2600We</NAME>
            <SPEC>0103</SPEC>
            <DRIVER />
            <FIRMINFO>
              <FIRM><ID>SUB2</ID><VERSION>B0000000000</VERSION></FIRM>
            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT />
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>
```

**Comment by Wikinaut** [comment]
(updated previous with the important response)

**Comment by Wikinaut** [comment]
@jcoffland have you read my updated https://github.com/CauldronDevelopmentLLC/oh-brother/issues/11#issuecomment-282952043 

You apparently have to "force" the list with `<VERSION>B0000000000</VERSION>` to get the current version.


Attribution to previous work of https://cbompart.wordpress.com/2014/05/26/brother-printer-firmware-part-2/ . Thanks!

**Comment by Wikinaut** [comment]
What's your suggestion now ? Do you plan to change your code to incorporate the new "method" ?

**Comment by Wikinaut** [comment]
@jcoffland I will send you a pr in some minutes...

**Comment by jcoffland** [comment]
I just push a new version.  Try this:

    ./oh-brother.py --category SUB2 <printer IP>

**Comment by Wikinaut** [comment]
@jcoffland In the meantime, after having submitted my pr, I read your mails to me. I could add 
`if name == 'ADS-2600We' and cat == 'SUB2'`
but I think, your new code (it works) is more flexible.

**Comment by Wikinaut** [comment]
Thanks for your swift reply, and help, and: this great code. And, oh my BROTHER, http is really bad.

**Comment by timofonic** [comment]
@jcoffland @Wikinaut Is this fixed? If yes, why is still open?
