### ISSUE TITLE
curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect

### ISSUE THREAD

**Issue by nitrogenblue** [CauldronDevelopmentLLC/oh-brother#14]
I tried to curl my request in an xml file to the brother server, but received this:

curl -X POST -d request.xml https://firmverup.brother.co.jp/kne_bh7_update_nt_ssl/ifax2.asmx/fileUpdate -H "Content-Type:text/xml" --sslv3

curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect

What do I do?

Thanks a lot for your work!

**Comment by jcoffland** [comment]
This is not the place to ask for help with curl.

**Comment by nitrogenblue** [comment]
I was wondering if Brother closed the firmware server for non Brother service centers? Because of this: "the server most likely requires a client certificate to connect"

In request.xml I used part of your code:

<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>MAIN</FIRMCATEGORY>
        <OS>MAC</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>

    <FIRMUPDATEINFO>
        <MODELINFO>
            <SELIALNO></SELIALNO>
            <NAME>HL-2250DN series</NAME>
            <SPEC></SPEC>
            <DRIVER></DRIVER>
            <FIRMINFO>
                <FIRM>
                    <ID>MAIN</ID>
                    <VERSION>1.15</VERSION>
                </FIRM>
                <FIRM>
                    <ID>BRNET</ID>
                    <VERSION>1.10</VERSION>
                </FIRM>
            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT></ERRBIT>
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>

**Comment by nitrogenblue** [comment]
Sorry, that was not the full code:

<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>MAIN</FIRMCATEGORY>
        <OS>MAC</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>

    <FIRMUPDATEINFO>
        <MODELINFO>
            <SELIALNO></SELIALNO>
            <NAME>HL-2250DN series</NAME>
            <SPEC></SPEC>
            <DRIVER></DRIVER>
            <FIRMINFO>
                <FIRM>
                    <ID>MAIN</ID>
                    <VERSION>1.15</VERSION>
                </FIRM>
                <FIRM>
                    <ID>BRNET</ID>
                    <VERSION>1.10</VERSION>
                </FIRM>
            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT></ERRBIT>
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>

**Comment by jcoffland** [comment]
If you have identified a bug with this software then please provide some context and open an new issue about that bug.

**Comment by nitrogenblue** [comment]
I was wondering if Brother closed the firmware server for non Brother service centers? Because of this: "the server most likely requires a client certificate to connect"

I cannot reach the server. No bug in this software.

**Comment by jcoffland** [comment]
That doesn't make sense.  People would still need to upgrade their printers at home using Windows.  So they would have to be able to contact Brother's severs.  Also, I just ran ``oh-brother.py`` on my machine and it worked so I was able to connect to Brother's servers.

**Comment by nitrogenblue** [comment]
Thanks a lot for running oh.brother.py . I must have done something wrong. I am trying to revive my Brother printer after a failed firmware update..

**Comment by jcoffland** [comment]
Good luck.
