### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by averagejoey2000** [CauldronDevelopmentLLC/oh-brother#17]
averagejoey2000@localhost ~ $ ./oh-brother.py 172.27.0.25
  File "./oh-brother.py", line 63
    print minidom.parseString(s).toprettyxml(indent = ' ')
                ^
SyntaxError: invalid syntax

**Comment by jcoffland** [comment]
Looks like you're running it with python3.  Try this:

    python2 ./oh-brother.py 172.27.0.25

**Comment by jsmithlabs** [comment]
I've added experimental support for both Python 2 and 3 in #21.
