### ISSUE TITLE
Thanks for this! A question about USB-connected printer

### ISSUE THREAD

**Issue by TriggerDingus** [CauldronDevelopmentLLC/oh-brother#27]
I am on a public wifi network and so I keep my printer connected only via USB cord. The command to execute your firmware tool is described as:
./oh-brother.py <ip address of printer>

I don't want to play around with commands to find I've bricked my printer, so I'm wondering if you could tell me what the command would be to execute the firmware update for a USB-connected printer?
./oh-brother.py <USB printer?>

**Comment by jcoffland** [comment]
This only works over Ethernet.
