### ISSUE TITLE
Add ability to override Model too?

### ISSUE THREAD

**Issue by Evengard** [CauldronDevelopmentLLC/oh-brother#34]
Hello!

Would it be possible to add ability to override the Model?
Rationale: this way it is actually possible to install IFAX (aka Internet Fax, aka Send to Email Server) on models which doesn't support it out of the box!

I managed to add IFAX to my DCP-9020CDW which doesn't have it (officially) with the help of this tool.
First, I did a bit of research and found out that my model and MFC-9330CDW are really similar (sharing the same service manual and apparently the same firmware). And MFC-9330CDW do have IFAX! So I guessed I could try to use it's.
Second, I replaced this line:

https://github.com/CauldronDevelopmentLLC/oh-brother/blob/736cf480a1db0a27d9ae7946494478e5322e30da/oh-brother.py#L133C2-L133C2 

with
```python
if name == 'MODEL': model = 'MFC-9330CDW'
```
Then I executed `python3 oh-brother.py --category IFAX 192.168.3.3` and... It actually worked! The IFAX got flashed and the new settings appeared, I tried to scan a document through the set up email server and that worked!
So thanks for your tool making magic happen!
Disclaimer: do similar stuff on your own risk, or don't.

Now, if a model override would be present I'd use it instead of patching the script itself.

**Comment by jcoffland** [comment]
Done.  See latest commit.

**Comment by Dragunovam** [comment]
@Evengard I can't seem to get a response for the IFAX category on my DCP-9020CDW. Could you share the file name of the IFAX flash file? I was planning on using it in the same way. Thanks
