### ISSUE TITLE
"NoneType object has no attribute 'text'"

### ISSUE THREAD

**Issue by ajmac** [CauldronDevelopmentLLC/oh-brother#4]
Getting the following on two distros (Ubuntu 14.04 and Gentoo);

```
   model = DCP-J4110DW
    spec = 0004
```

   firmwares
            category = FIRM, version = F1311010648:CB1D

Updating FIRM version F1311010648:CB1D
Looking up printer firmware... done
Traceback (most recent call last):
  File "./oh-brother.py", line 226, in <module>
    update_firmware(entry['cat'], entry['version'])
  File "./oh-brother.py", line 176, in update_firmware
    firmwareURL = xml.find('FIRMUPDATEINFO/PATH').text
AttributeError: 'NoneType' object has no attribute 'text'

Any hints?

**Comment by jcoffland** [comment]
I've committed a new version which has a verbose mode and handles this error better.  Try adding the ``-v`` option and post the output then we can try to figure out what Brother is returning.  I have not tested this with your printer type.  It may or may not be possible to update your firmware with this method.

**Comment by ajmac** [comment]
Thanks for the quick reply, here's the output.  Doesn't look like it's finding where the updated firmware should be if I'm reading it right?  I know that my printer is not up to date, it's on version F when J is available.

Getting SNMP data from printer at 192.168.2.5... done
[[(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.1'), OctetString('MODEL="DCP-J4110DW"'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.2'), OctetString('CTYPE="MFC"'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.3'), OctetString('SERIAL="E71384A4F338835"'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.4'), OctetString('SPEC="0004"'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.5'), OctetString('FIRMID="FIRM"'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.6'), OctetString('FIRMVER="F1311010648:CB1D"'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.7'), OctetString(hexValue='0c'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.8'), OctetString(hexValue='0c'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.9'), OctetString(hexValue='0c'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.10'), OctetString(hexValue='0c'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.11'), OctetString(hexValue='0c'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.12'), OctetString(hexValue='0c'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.13'), OctetString(hexValue='0c'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.14'), OctetString(hexValue='0c'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.15'), OctetString(hexValue='0c'))], [(ObjectName('1.3.6.1.4.1.2435.2.4.3.99.3.1.6.1.2.16'), OctetString(hexValue='0c'))]]

      serial = E71384A4F338835
       model = DCP-J4110DW
        spec = 0004
   firmwares
            category = FIRM, version = F1311010648:CB1D


Updating FIRM version F1311010648:CB1D
Looking up printer firmware... done
<?xml version="1.0" ?>
<RESPONSEINFO>
 <FIRMUPDATEINFO>
  <VERSIONCHECK>2</VERSIONCHECK>
 </FIRMUPDATEINFO>
</RESPONSEINFO>

No firmware update info path found

**Comment by jcoffland** [comment]
Either Brother does not support updating this printer's firmware like this or the request needs to be constructed differently.  If you are able to find more information on the update procedure for your particular printer, perhaps by scouring the Web, I'd be happy to update the tool.

**Comment by ajmac** [comment]
On Wed, 18 Nov 2015 01:53:44 -0800
Joseph Coffland wrote:

> Either Brother does not support updating this printer's firmware like this or the request needs to be constructed differently.  If you are able to find more information on the update procedure for your particular printer, perhaps by scouring the Web, I'd be happy to update the tool.

OK, thanks anyway - if I can find anything useful I'll let you know.  The firmware update tool for OSX is actually a Java .jar (though packaged in a .dmg) so potentially useful on Linux too - I've run it briefly and it works up to the point of searching for a printer but it hasn't found mine.  I'll need to install Java on a Mac and see if it works any better there...

-- 
AJ

**Comment by jcoffland** [comment]
I think this problem can not be solved by running:

    ./oh-brother.py --category FIRM <printer IP>
